# test yaml

model_name: "flashi2v"
pipeline_name: "flashi2v"
seed: 1024

prompt_txt: "assets/i2v/prompts.txt"
image_txt: "assets/i2v/images.txt"

output_dir: "samples/flashi2v_14b_49f_480p"

num_frames: 49
height: 480
width: 832
save_fps: 16
batch_size: 2

fsdp_size: 8
cp_size: 2
use_context_parallel: True
reshard_after_forward: null
weight_dtype: "bf16"
save_with_dcp_api: False

model_config:
  dim: 5120
  ffn_dim: 13824
  freq_dim: 256
  in_dim: 16
  num_heads: 40
  num_layers: 40
  out_dim: 16
  text_len": 512
  low_freq_energy_ratio: 0.1
  fft_return_abs: True
  conv3x3x3_proj: False
  pretrained_model_dir_or_checkpoint: "/mnt/data2/FlashI2V/flashi2v_14b_49f_480p"

scheduler_config:
  scheduler_name: "flashi2v_flow_matching"
  num_inference_steps: 50
  shift: 7.0
  guidance_scale: 5.0

vae_config:
  vae_path: "/mnt/data2/Wan2.1-T2V-14B/Wan2.1_VAE.pth"
  dtype: "fp32"

text_encoder_config:
  text_len: 512
  checkpoint_path: "/mnt/data2/Wan2.1-T2V-14B/models_t5_umt5-xxl-enc-bf16.pth"
  text_tokenizer_path: "/mnt/data2/Wan2.1-T2V-14B/google/umt5-xxl"
  use_fsdp: True
