# test yaml

model_name: "wan_t2v"
pipeline_name: "t2v"
seed: 1024

prompt_txt: "assets/simple_prompts.txt"
output_dir: "samples/wan_t2v"

num_frames: 49
height: 480
width: 832
save_fps: 16
batch_size: 1

fsdp_size: 2
cp_size: 2
use_context_parallel: False
reshard_after_forward: null
weight_dtype: "bf16"
save_with_dcp_api: False

wandb_config:
  project_name: "test_fsdp"
  exp_name: "test_fsdp"

model_config:
  pretrained_model_dir_or_checkpoint: "/hdd/gyy/Wan2.1-T2V-1.3B"

scheduler_config:
  scheduler_name: "flow_matching"
  num_inference_steps: 50
  shift: 7.0
  guidance_scale: 5.0

vae_config:
  vae_path: "/hdd/gyy/Wan2.1-T2V-1.3B/Wan2.1_VAE.pth"
  dtype: "fp32"

text_encoder_config:
  text_len: 512
  checkpoint_path: "/hdd/gyy/Wan2.1-T2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth"
  text_tokenizer_path: "/hdd/gyy/Wan2.1-T2V-1.3B/google/umt5-xxl"
  use_fsdp: True
